[package]
name = "bevy_tank_war"
version = "0.1.0"
authors = ["Kirill Kuzminykh <cykooz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version="0.4.0", features = ["vorbis"]}
rand = { version = "0.7.2", features = ["small_rng"] }
noise = "0.6.0"
itertools = "0.8.1"
bevy_prototype_lyon = "0.1.5"
bytecount = "0.6.0"
env_logger = "0.8.1"
line_drawing = "0.8.0"


[profile.dev.package.'*']
opt-level = 3


[profile.release]
#lto = true
opt-level = 3
#codegen-units = 1
